# Generated by Django 3.0.3 on 2022-05-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
