# Generated by Django 3.0.3 on 2022-05-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='chest_pain_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='cholesterol',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='exercise_induced_angina',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='fasting_blood_sugar',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='max_heart_rate_achieve',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='num_major_vessels',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='rest_ecg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='resting_blood_pressure',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='sex',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='st_depression',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='st_slope',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='thalassemia',
            field=models.IntegerField(default=0),
        ),
    ]
