# Generated by Django 3.0.3 on 2022-05-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220528_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='predict',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
